-- CREATE SEQUENCE SEQ_CB_USER;
CREATE SEQUENCE SEQ_CMS_USER
INCREMENT BY 1
START WITH 1;

-- 创建用户信息表
CREATE TABLE CMS_USER (
  ID         NUMBER        NOT NULL PRIMARY KEY,
  REAL_NAME  VARCHAR2(100) NOT NULL,
  LOGIN_NAME VARCHAR2(100) NOT NULL,
  PASSWORD VARCHAR2(100) NOT NULL
);

